### ISSUE TITLE
RGB, RGBA features

### ISSUE THREAD

**Issue by florinpop17** [Bloggify/colors#4]
It would be nice if you could provide alongside HEX colors, also RGB and RGBA. Maybe I could help you with this 😄

**Comment by IonicaBizau** [comment]
That would be amazing! :heart: 

It could be done here, in the `flat-colors` module: https://github.com/Bloggify/cute-colors (to export these formats)

The other way would be to convert them on the fly, in this app. :smile:

**Comment by florinpop17** [comment]
Not sure how many other projects depend on `cute-colors`, but as I've seen there we just need to convert the JSON's array of strings into array of objects. I think we could write a script to do this automatically and then update this project to use all the variants. 🙂

**Comment by IonicaBizau** [comment]
That works. And we can bump the major version. :)

**Comment by IonicaBizau** [comment]
I am closing this for now, but contributions are welcome.
